### ISSUE TITLE
It tells me:"no application can esecute this action"

### ISSUE THREAD

**Issue by zerokod** [acasaccia/cordova-socialshare-plugin#4]
Hi this plugin seem working but when i click to share it doesn't share on any social network no facebook no twitter even if they are installated in the device, could you help m to understand why? did i forgot anything this is my code 

function shareIt(){

window.plugins.SocialShare.share(
    successCallbackS,
    errorCallbackS,
    {
        dialogTitle : 'Share using:',         // Title of the native dialog
        url : "http://google.com",          // Url to be shared
        text : "Take a look at this {{url}}", // Text to be shared where possible (not in Facebook)
                                              // {{url}} will be replaced by given url
        mailSubject : "Great news for you"    // Subject of the email if users select a mail client
    }
);

}

 function successCallbackS(){
      alert('share ok');
   }  
   
   function errorCallbackS(){
   		alert('Si è verificato un errore');
   } 

please help me thank you regards
Roberta

**Comment by acasaccia** [comment]
There used to be a bug when the first application in the list of supported ones wasn't installed, it has been fixed in a50faa54882f22bd0f9b7ebf573e9caddb6feb9c
